### PR TITLE
rename repo to qt-extras

### PR DESCRIPTION
**Pull request by tlambert03**

### CODE REVIEW

**Review by jni — APPROVED** [review]
I'm approving, but just to throw another one out there that just occurred to me: superqt. What do you think?

**Comment by tlambert03** [comment]
More adorable, slightly less apropos :)
I could be ok with it

**Comment by jni** [comment]
> slightly less apropos :)

I like all of these for this library 😂 

Screen Shot 2021-06-23 at 12 08 12 pm

**Comment by tlambert03** [comment]
gonna go with `superqt`

**Pull request closed without merging**
